dist: xenial
language: python
python: 3.7.4
install:
  - pip install -r requirements.txt
  - pip install -e .

services:
  - postgresql

env:
  - DJANGO=2.2.8 DB=postgres

script:
  - python manage.py test